name: mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter_inappwebview: ^6.0.0
  image_picker: ^0.8.4+4
  path_provider: ^2.1.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  page_transition: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.0
  avatar_glow: ^3.0.1
  file_selector_windows: 0.9.3+1
  http: ^1.2.1
  camera: ^0.11.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  outline_gradient_button: ^2.0.1+1
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  flutter_vision: ^1.1.4
  url_launcher: ^6.0.20
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.6
  provider: ^6.0.1
  webview_flutter: ^4.0.0
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/pagesatu.jpg
    - assets/images/pagedua.png
    - assets/images/pagetiga.jpg
    - assets/images/logohs.png
    - assets/images/forgot.jpg
    - assets/images/login.jpg
    - assets/images/register.jpg
    - assets/images/p1.png
    - assets/images/p2.png
    - assets/images/p3.png
    - assets/images/p4.png
    - assets/images/checkemail.jpg
    - assets/images/yt.png
    - assets/images/poto1.png
    - assets/images/poto2.png
    - assets/images/poto3.png
    - assets/best_float32.tflite
    - assets/labels.txt


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
