import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class checkemail extends StatelessWidget {
  const checkemail({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Checkemail(),
        ]),
      ),
    );
  }
}

class Checkemail extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 42,
                top: 0,
                child: Container(
                  width: 314,
                  height: 330,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/314x330"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 324,
                child: Container(
                  width: 319,
                  height: 374,
                  decoration: ShapeDecoration(
                    color: Colors.white.withOpacity(0.10000000149011612),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 3, color: Color(0xFF5882C1)),
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 341,
                child: Container(
                  width: 293,
                  height: 315.17,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 45,
                        top: 0,
                        child: Container(
                          width: 192,
                          height: 40,
                          padding: const EdgeInsets.only(top: 20, left: 20, right: 20),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Text(
                                'Check your mail',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 20,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 11,
                        top: 42,
                        child: Container(
                          width: 267,
                          height: 74,
                          padding: const EdgeInsets.only(left: 20, right: 20, bottom: 18),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 281,
                                height: 47,
                                child: Text(
                                  'We sent a reset link, Enter 5 digit code that mentioned in the email',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF989898),
                                    fontSize: 15,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 0.09,
                                    letterSpacing: -0.50,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 41,
                        top: 129,
                        child: Container(
                          width: 42,
                          height: 41,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 96,
                        top: 129,
                        child: Container(
                          width: 42,
                          height: 41,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 151,
                        top: 129,
                        child: Container(
                          width: 43,
                          height: 41,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 209,
                        top: 129,
                        child: Container(
                          width: 43,
                          height: 41,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 187,
                        child: Container(
                          width: 293,
                          height: 20,
                          padding: const EdgeInsets.only(bottom: 4),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Opacity(
                                opacity: 0.60,
                                child: Text(
                                  '01:00',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 15,
                                    fontFamily: 'Work Sans',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 39,
                        top: 226,
                        child: SizedBox(
                          width: 129,
                          height: 16,
                          child: Text(
                            'Didn’t get a code? ',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 185,
                        top: 226,
                        child: SizedBox(
                          width: 66,
                          height: 33,
                          child: Text(
                            'Resend',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF648DDB),
                              fontSize: 15,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w600,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 57,
                        top: 267,
                        child: Container(
                          width: 195,
                          height: 48.17,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 195,
                                  height: 48.17,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF6C96C5),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x1E000000),
                                        blurRadius: 1,
                                        offset: Offset(0, 2),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 40,
                                top: 12,
                                child: SizedBox(
                                  width: 116,
                                  height: 23,
                                  child: Text(
                                    'Verify Code',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 15,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}